<a href="https://colab.research.google.com/github/AliefReefandi/Grokking-Deep-Learning/blob/main/Chapter_06_Building_Your_First_Deep_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 6 — Building Your First Deep Neural Network

## Tujuan Pembelajaran

Pada chapter ini kita akan membangun neural network yang memiliki
lebih dari satu layer dan mempelajari bagaimana backpropagation
digunakan untuk melakukan learning.

Setelah menyelesaikan chapter ini, kita diharapkan dapat:

- Memahami konsep deep neural network.
- Memahami penggunaan hidden layer.
- Memahami matrix dalam neural network.
- Memahami stochastic, batch, dan full gradient descent.
- Memahami bagaimana neural network menemukan correlation.
- Memahami konsep backpropagation.
- Memahami fungsi aktivasi ReLU.
- Membangun deep neural network sederhana menggunakan NumPy.

## 2. Streetlight Problem

Chapter ini menggunakan contoh sederhana berupa lampu lalu lintas.

Network diberikan pola tiga lampu:

[1, 0, 1]
[0, 1, 1]
[0, 0, 1]
[1, 1, 1]

Kemudian network harus memprediksi apakah orang akan:

- WALK
- STOP

Tujuan utamanya adalah membuat neural network belajar hubungan
antara pola lampu dengan keputusan WALK atau STOP.

Dari data tersebut, network akan menemukan bahwa lampu bagian tengah
memiliki hubungan paling kuat dengan keputusan untuk berjalan.

## 3. Preparing the Data

Pada supervised learning terdapat dua dataset:

1. Data yang diketahui oleh network.
2. Data yang ingin diprediksi.

Pada streetlight problem:

Input:
Pola lampu

Output:
WALK atau STOP

Data input dan output kemudian direpresentasikan menggunakan angka
agar dapat diproses oleh neural network.

## 4. Matrix dan Matrix Relationship

Data streetlight dapat disimpan sebagai matrix.

Setiap baris mewakili satu contoh data.

Setiap kolom mewakili satu lampu.

Contoh:

[
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 1],
 [1, 1, 1]
]

Dengan menggunakan matrix, neural network dapat melakukan operasi
terhadap banyak data dengan lebih mudah.

Dalam neural network, matrix juga digunakan untuk menyimpan weight
yang menghubungkan satu layer dengan layer lainnya.

In [1]:
import numpy as np

streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1]
])

walk_vs_stop = np.array([
    [1, 1, 0, 0]
]).T

print("Streetlights:")
print(streetlights)

print("\nWalk vs Stop:")
print(walk_vs_stop)

Streetlights:
[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]

Walk vs Stop:
[[1]
 [1]
 [0]
 [0]]


## 5. Membangun Neural Network

Sekarang kita mulai menggunakan dua layer.

Struktur network:

Input Layer → Hidden Layer → Output Layer

Layer pertama menerima data streetlight.

Hidden layer membuat intermediate representation dari input.

Output layer menghasilkan prediksi WALK atau STOP.

Setiap hubungan antar-layer memiliki weight.

In [2]:
np.random.seed(1)

def relu(x):
    return (x > 0) * x


alpha = 0.2
hidden_size = 4

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1

layer_0 = streetlights[0]
layer_1 = relu(np.dot(layer_0, weights_0_1))
layer_2 = np.dot(layer_1, weights_1_2)

print("Layer 0:")
print(layer_0)

print("\nLayer 1:")
print(layer_1)

print("\nLayer 2:")
print(layer_2)

Layer 0:
[1 0 1]

Layer 1:
[-0.          0.51828245 -0.         -0.        ]

Layer 2:
[0.39194327]


## 6. Learning the Whole Dataset

Network tidak cukup hanya melakukan satu prediction.

Network harus mempelajari seluruh dataset.

Caranya adalah dengan melakukan proses berikut untuk setiap data:

1. Prediction
2. Menghitung error
3. Menghitung delta
4. Meng-update weight

Proses tersebut dilakukan berulang kali sampai error menjadi semakin kecil.

## 7. Full, Batch, dan Stochastic Gradient Descent

Terdapat beberapa cara untuk melakukan update weight.

### Stochastic Gradient Descent

Weight diperbarui setelah setiap satu contoh data.

Contoh:

Data 1 → update
Data 2 → update
Data 3 → update
Data 4 → update

### Full Gradient Descent

Network menghitung error dari seluruh dataset terlebih dahulu,
kemudian melakukan update weight berdasarkan rata-rata error.

### Batch Gradient Descent

Update dilakukan setelah sejumlah data tertentu.

Contohnya:

8 data → update
8 data → update
8 data → update

## 8. Neural Networks Learn Correlation

Neural network pada dasarnya berusaha menemukan hubungan atau
correlation antara input dan output.

Pada streetlight problem, hasil training menunjukkan bahwa weight
untuk lampu tengah menjadi jauh lebih besar dibandingkan weight
lampu lainnya.

Artinya, network menemukan bahwa lampu tengah memiliki hubungan
yang kuat dengan keputusan WALK atau STOP.

## 9. Overfitting dan Conflicting Pressure

Neural network dapat mengalami kondisi ketika network terlalu fokus
pada pola tertentu dari data training.

Kondisi tersebut disebut overfitting.

Pada training, setiap contoh dapat memberikan "pressure" terhadap
weight:

- Up pressure → weight perlu dinaikkan.
- Down pressure → weight perlu diturunkan.

Jika data memiliki pola yang bertentangan, weight dapat menerima
pressure dari arah yang berbeda.

## 10. Learning Indirect Correlation

Tidak semua hubungan antara input dan output bersifat langsung.

Terkadang input harus diproses terlebih dahulu agar menghasilkan
informasi yang berguna untuk output.

Contohnya pada gambar kucing:

Pixel individual mungkin tidak cukup untuk menentukan apakah
gambar tersebut memiliki kucing.

Namun kombinasi beberapa pixel dapat membentuk pola seperti:

- telinga
- mata
- rambut
- bentuk wajah

Hidden layer dapat membantu membuat intermediate dataset yang
mewakili pola-pola tersebut.

## 11. Stacking Neural Networks

Deep neural network dapat dibuat dengan menumpuk beberapa neural network.

Strukturnya:

Layer 0 → Layer 1 → Layer 2

Output dari network pertama menjadi input untuk network berikutnya.

Dengan demikian, setiap layer dapat membuat representasi data yang
berbeda sebelum data tersebut digunakan oleh layer berikutnya.

## 12. Backpropagation

Backpropagation digunakan untuk menentukan seberapa besar kontribusi
masing-masing weight terhadap error.

Prosesnya dilakukan dari output menuju layer sebelumnya.

Contoh:

Layer 0 → Layer 1 → Layer 2

Jika Layer 2 memiliki error, kita perlu mengetahui:

"Seberapa besar Layer 1 berkontribusi terhadap error tersebut?"

Caranya adalah menggunakan weight yang menghubungkan Layer 1
dengan Layer 2.

Delta pada layer sebelumnya dihitung berdasarkan delta pada layer
berikutnya dan weight yang menghubungkannya.

Dengan demikian, error dapat "dipropagasikan" kembali menuju layer
sebelumnya.

## 13. Linear vs Nonlinear

Deep neural network membutuhkan nonlinearitas agar hidden layer
dapat mempelajari pola yang lebih kompleks.

Pada chapter ini digunakan fungsi aktivasi ReLU.

ReLU secara sederhana:

ReLU(x) = x, jika x > 0
ReLU(x) = 0, jika x <= 0

Artinya nilai negatif diubah menjadi 0.

In [3]:
def relu(x):
    return (x > 0) * x

## 14. First Deep Neural Network

Sekarang kita menggabungkan konsep-konsep sebelumnya:

- Matrix
- Multiple weights
- Multiple layers
- ReLU
- Gradient descent
- Delta
- Backpropagation

Network yang dibuat:

Input Layer
     ↓
Hidden Layer
     ↓
Output Layer

Network kemudian dilatih menggunakan data streetlight.

## 15. Backpropagation in Code

Pada proses backpropagation:

1. Hitung prediction.
2. Hitung error.
3. Hitung delta pada output.
4. Propagasikan delta ke hidden layer.
5. Gunakan delta untuk menghitung weight_delta.
6. Update weight.

Untuk hidden layer digunakan derivative dari ReLU.

Jika output ReLU bernilai 0, maka derivative-nya juga 0 sehingga
node tersebut tidak memberikan kontribusi pada update.

## 16. Implementasi Lengkap

Kode berikut menggabungkan seluruh konsep Chapter 6 menjadi sebuah
deep neural network sederhana yang belajar dari streetlight dataset.

In [4]:
import numpy as np

np.random.seed(1)


def relu(x):
    return (x > 0) * x


def relu2deriv(output):
    return output > 0


streetlights = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
    [1, 1, 1]
])

walk_vs_stop = np.array([
    [1, 1, 0, 0]
]).T

alpha = 0.2
hidden_size = 4

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1


for iteration in range(60):

    layer_2_error = 0

    for i in range(len(streetlights)):

        layer_0 = streetlights[i:i+1]

        # Forward propagation
        layer_1 = relu(
            np.dot(layer_0, weights_0_1)
        )

        layer_2 = np.dot(
            layer_1,
            weights_1_2
        )

        # Calculate error
        layer_2_error += np.sum(
            (layer_2 - walk_vs_stop[i:i+1]) ** 2
        )

        # Backpropagation
        layer_2_delta = (
            layer_2 - walk_vs_stop[i:i+1]
        )

        layer_1_delta = (
            layer_2_delta.dot(weights_1_2.T)
            * relu2deriv(layer_1)
        )

        # Update weights
        weights_1_2 -= (
            alpha *
            layer_1.T.dot(layer_2_delta)
        )

        weights_0_1 -= (
            alpha *
            layer_0.T.dot(layer_1_delta)
        )

    if iteration % 10 == 9:
        print("Error:", layer_2_error)

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


## 17. Penjelasan Kode

### `layer_0`

Merupakan input berupa pola streetlight.

### `weights_0_1`

Weight yang menghubungkan input layer dengan hidden layer.

### `layer_1`

Hidden layer yang menghasilkan intermediate representation.

### `weights_1_2`

Weight yang menghubungkan hidden layer dengan output layer.

### `layer_2`

Output/prediction dari network.

### `layer_2_delta`

Menunjukkan seberapa besar prediction pada output perlu diperbaiki.

### `layer_1_delta`

Delta yang telah dipropagasikan kembali ke hidden layer.

### `weights_1_2` dan `weights_0_1`

Diperbarui menggunakan hasil backpropagation agar error semakin kecil.

## 19. Kesimpulan

Chapter 6 memperkenalkan konsep penting dalam deep learning,
yaitu deep neural network dan backpropagation.

Dengan menggunakan hidden layer, neural network tidak hanya mencari
direct correlation antara input dan output, tetapi juga dapat membuat
intermediate representation untuk menemukan indirect correlation.

Backpropagation memungkinkan error dari output digunakan untuk
menentukan bagaimana weight pada layer sebelumnya harus diperbarui.

Dengan demikian, neural network dapat belajar dari error secara
bertahap hingga menghasilkan prediction yang semakin baik.

Konsep pada chapter ini menjadi dasar untuk memahami arsitektur
neural network yang lebih kompleks pada chapter berikutnya.